# ███╗░░██╗░█████╗░███╗░░░███╗███████╗██████╗░░░░█████╗░██╗░░██╗███████╗░██████╗████████╗
# ████╗░██║██╔══██╗████╗░████║██╔════╝██╔══██╗░░██╔══██╗██║░░██║██╔════╝██╔════╝╚══██╔══╝
# ██╔██╗██║███████║██╔████╔██║█████╗░░██║░░██║░░██║░░╚═╝███████║█████╗░░╚█████╗░░░░██║░░░
# ██║╚████║██╔══██║██║╚██╔╝██║██╔══╝░░██║░░██║░░██║░░██╗██╔══██║██╔══╝░░░╚═══██╗░░░██║░░░
# ██║░╚███║██║░░██║██║░╚═╝░██║███████╗██████╔╝░░╚█████╔╝██║░░██║███████╗██████╔╝░░░██║░░░
# ╚═╝░░╚══╝╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝╚═════╝░░░░╚════╝░╚═╝░░╚═╝╚══════╝╚═════╝░░░░╚═╝░░░

# Developer / Разработчик: ILeZzoV

# Socials / Ссылки:
# • Contact with me / Связаться: https://t.me/ilezovofficial
# • Telegram Channel / Телеграм канал: RUS: https://t.me/ilezzov
# • GitHub: https://github.com/ilezzov-code

# By me coffee / Поддержать разработчика:
# • DA: https://www.donationalerts.com/r/ilezov
# • YooMoney: https://yoomoney.ru/to/4100118180919675
# • Telegram Gift: https://t.me/ilezovofficial
# • TON: UQCInXoHOJAlMpZ-8GIHqv1k0dg2E4pglKAIxOf3ia5xHmKV
# • BTC: 1KCM1QN9TNYRevvQD63UF81oBRSK67vCon
# • Card: 5536914188326494

# Supporting messages languages / Доступные языки сообщений:
# ru-RU, en-US
language: "en-US"

# Check the plugin for updates
# Проверять плагин на наличие обновлений
check_updates: true

# Enable / Disable the option to name a block | Включить / Отключить возможность давать имя блоку
# Supporting blocks / Поддерживаемые блоки: CHEST (сундук), TRAPPED_CHEST (сундук-ловушка),
# BARREL (бочка), FURNACE (печка), SMOKER (коптильня), BLAST_FURNACE (плавильня), HOPPER (воронка),
# DISPENSER (раздатчик), DROPPER (выбрасыватель), BREWING_STAND (варочная стойка), SHULKER_BOX (шалкер бокс)
supporting_block:
  - CHEST
  - TRAPPED_CHEST
  - BARREL
  - FURNACE
  - SMOKER
  - BLAST_FURNACE
  - HOPPER
  - DISPENSER
  - DROPPER
  - BREWING_STAND
  - SHULKER_BOX

# Maximum distance to the block / Максимальная дистанция до блока
max_distance: 5

# Enable supporting WorldGuard / Включить поддержку WorldGuard
# WorldGuars is a Minecraft plugin — https://github.com/EngineHub/WorldGuard
support_worldguard: true

# Item's name settings / Настройки имени блока
name_settings:
  # Enable support color name / Включить поддержку цветных имен
  support_color: true
  # Max name length / Максимальная длинна имени
  max_name_length: 25
  # Save the name when the block is destroyed / Сохранять имя при разрушении блока
  save_for_breaking: false
  # Forbid giving a name through an anvil / Запретить давать имя через наковальню
  cancel_anvil: true
  # Support for spaces in the name / Поддержка пробелов в имени
  support_spaces: true

# Enable / Disable plugin commands
# Включить / Выключить команды плагина
command_settings:
  enable_set: true # Enable command /nc set | Включить команду /nc set
  enable_clear: true # Enable command /nc clear | Включить команду /nc clear
  cooldown: 5 # Cooldown in using commands in seconds | Задержка на использование команд в секундах

# Don't edit this / Не редактируйте это
config_version: ${project.version}