Messages:
  create-new-file: "Файл &6%s &rбыл создан"
  add-new-keys-to-file: "Файл &6%s &&rбыл обновлен. Там появились новые настройки"
  has-error: "Возникла ошибка: &c%s"
  plugin-enable: "Плагин успешно &aвключен \n&rРазработчик: &6%s \n&rВерсия: &6%s \n&rСвязаться: &6%s"
  plugin-disable: "Плагин успешно &cвыключен \n&rРазработчик: &6%s \n&rВерсия: &6%s \n&Связаться: &6%s"

